name: alphabet_list_view_example
description: Demonstrates how to use alphabet_list_view.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  alphabet_list_view:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.1.1
  dart_code_metrics: ^5.5.1

flutter:
  uses-material-design: true
