/*
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYwzsGuYPO1IAE0f2hAcCd03bt8tAGA-c',
    appId: '1:407406091517:web:6103b72f01afb440f1f294',
    messagingSenderId: '407406091517',
    projectId: 'dionniebee-488f2',
    authDomain: 'dionniebee-488f2.firebaseapp.com',
    storageBucket: 'dionniebee-488f2.appspot.com',
    measurementId: 'G-XWN83R6KKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZTLsj3XFDjKUQfo0g-06kDsLjNBvoc2c',
    appId: '1:407406091517:android:4e6606e341e91af2f1f294',
    messagingSenderId: '407406091517',
    projectId: 'dionniebee-488f2',
    storageBucket: 'dionniebee-488f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz-18IkI2NGdmeb1HZw3OvenVOge-H3b0',
    appId: '1:407406091517:ios:a15a59263f0a0580f1f294',
    messagingSenderId: '407406091517',
    projectId: 'dionniebee-488f2',
    storageBucket: 'dionniebee-488f2.appspot.com',
    iosClientId:
        '407406091517-sr0iik0ka9t848r1eebhva3mui4kvd53.apps.googleusercontent.com',
    iosBundleId: 'com.dionniestudios.dionniebee',
  );
}*/
