name: ez_onboarding
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '^2.12.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  loop_page_view: ^1.2.0
  page_view_indicators: ^2.0.0
