name: alphabet_list_view
description: A ListView with sticky headers and an iOS-like clickable sidebar.
version: 0.1.7
repository: https://github.com/cosee/alphabet_list_view

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_sticky_header: ^0.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.1.1
  dart_code_metrics: ^5.5.1

flutter:
